bookr/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
import reviews.views
from reviews import views
from users import views as users_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookr/', reviews.views.base, name='reviews-home'),
    path('book_list/', reviews.views.book_list, name='book_list'),
    path('register/', users_views.register, name='register'),
    path('profile/', users_views.profile, name='profile'),
    path('', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('search/', reviews.views.book_search, name='book_search'),
    path('', include('reviews.urls')),
    path('books/<int:id>/submit_review/', reviews.views.submit_review, name='submit_review'),
    path('books/genre/<str:genre_type>/', reviews.views.books_by_genre, name='books_by_genre'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from .views import BookCreateView, ContributorCreateView, BookUpdateView
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('book_detail/<int:id>/', views.book_detail, name='book_detail'),
    path('book/new/', BookCreateView.as_view(), name='book-create'),
    path('book/new/contributor', ContributorCreateView.as_view(), name='contributor-create'),
    path('book_detail/<int:pk>/update/', BookUpdateView.as_view(), name='book-update')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/models.py
from django.db import models
from django.contrib import auth
from PIL import Image
from django.urls import reverse

# Create your models here.
class Publisher(models.Model):
    '''A company that publishes books'''
    name = models.CharField(max_length=50, help_text = 'the name of the publisher',)
    website = models.URLField(help_text="the publisher's website.")
    email = models.EmailField(help_text="the publisher's email address")
    def __str__(self):
        return self.name

class Book(models.Model):
    '''A published book'''
    title = models.CharField(max_length=70, help_text='the title of the book')
    author = models.CharField(max_length=70, help_text='author of the book', null=True)
    publication_date = models.DateField(verbose_name='date the book was published', null=True)
    isbn = models.CharField(max_length=20, verbose_name='the isbn number of the book', unique=True, null=True)
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE, null=True)
    contributors = models.ManyToManyField('Contributor', through='BookContributor')
    image = models.ImageField(default='no_image.JPEG', upload_to='book_images', null=True, blank=True)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book_detail', kwargs={'id': self.id})

class Contributor(models.Model):

    first_names = models.CharField(max_length=50, help_text='the contributors first names')
    last_names = models.CharField(max_length=50, help_text='the contributors last name')
    email = models.EmailField(help_text='the contributors email')
    def __str__(self):
        return self.first_names

    def get_absolute_url(self):
        return reverse('book-create')

class BookContributor(models.Model):
    class ContributionRole(models.TextChoices):
        AUTHOR = 'AUTHOR', 'author'
        CO_AUTHOR = 'CO_AUTHOR', 'co_author'
        EDITOR = 'EDITOR', 'editor'

    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    contributor = models.ForeignKey(Contributor, on_delete=models.CASCADE)
    role = models.CharField(verbose_name='the role this contributor had in the book', choices=ContributionRole.choices, max_length=20)

class Review(models.Model):
    content = models.TextField(help_text='the review text')
    rating = models.IntegerField(help_text='the rating the reviewer has given')
    date_created = models.DateTimeField(auto_now_add=True,
        help_text='the date and time the review was created'
    )
    date_edited = models.DateTimeField(null=True, help_text='the date and time the review was last edited')
    creator = models.ForeignKey(auth.get_user_model(), on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, help_text='the book that this review is for')

class Genre(models.Model):
    class GenreType(models.TextChoices):
        Horror = 'HORROR', 'horror'
        Comedy = 'COMEDY', 'comedy'
        Romance = 'ROMANCE', 'romance'
        Action = 'ACTION', 'action'
        Sci_Fi = 'SCI-FI', 'sci-fi'
        science ='SCIENCE', 'science'

    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    genre = models.CharField(verbose_name='the genre of this book', choices=GenreType.choices, max_length=20)

reviews/forms.py
from django import forms
from .models import *

class BookSearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)



class BookForm(forms.ModelForm):
    contributors = forms.ModelMultipleChoiceField(queryset=Contributor.objects.all(), required=False, widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Book
        fields = ['title', 'author', 'publisher', 'contributors', 'isbn', 'publication_date']
        widgets = {
            'publication_date': forms.DateInput(attrs={'type': 'date'}),
            'contributors': forms.SelectMultiple(attrs={'class': 'form-select'}),
        }


class BookImageForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['image']


class ContributorForm(forms.ModelForm):
    class Meta:
        model = Contributor
        fields = ['first_names', 'last_names', 'email']

reviews/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from reviews.models import *
from django.http import Http404
from .utils import average_rating
from .forms import BookSearchForm, BookForm, BookImageForm, ContributorForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


def base(request):
    return render(request, 'base.html')


def book_search(request):
    if 'query' in request.GET:
        query = request.GET['query']
        results = Book.objects.filter(title__icontains=query)
    else:
        results = None

    form = BookSearchForm()

    return render(request, 'search.html', {'results': results, 'form': form})

def book_list(request):
    books = Book.objects.all()
    genres = Genre.objects.values('genre').distinct()
    return render(request, 'book_list.html', {'books': books, 'genres': genres})

def book_detail(request, id):
    book = get_object_or_404(Book, id=id)
    reviews = Review.objects.filter(book=book)
    return render(request, 'book_detail.html', {'book': book, 'reviews': reviews,})

def submit_review(request, id):
    if request.method == 'POST':
        book = get_object_or_404(Book, pk=id)
        creator = request.user  # Corrected line
        rating = request.POST.get('rating')
        content = request.POST.get('comment')
        review = Review.objects.create(creator=creator, book=book, rating=rating, content=content)
        return redirect('book_detail', id=id)
    return HttpResponseBadRequest()



def books_by_genre(request, genre_type):
    books = Book.objects.filter(genre__genre=genre_type)
    return render(request, 'genresort.html', {'genre_type': genre_type, 'books': books})

def contributorsort(request, contributor_name):
    contributors = Contributor.objects.all()
    return render(request, 'book_form.html', {'contributors': contributors})


class BookCreateView(LoginRequiredMixin, CreateView):
    model = Book
    form_class = BookForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['image_form'] = BookImageForm()
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        image_form = BookImageForm(request.POST, request.FILES)
        
        if form.is_valid() and image_form.is_valid():
            form.instance.author = self.request.user
            form.instance.image = image_form.cleaned_data['image']
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        response = super().form_valid(form)
        return response

class ContributorCreateView(CreateView):
    model = Contributor
    form_class = ContributorForm
    template_name = 'reviews/contributor_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class BookUpdateView(LoginRequiredMixin, UpdateView):
    model = Book
    form_class = BookForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['image_form'] = BookImageForm()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        image_form = BookImageForm(request.POST, request.FILES)
        if form.is_valid() and image_form.is_valid():
            return self.form_valid(form, image_form)
        else:
            return self.form_invalid(form, image_form)

    def form_valid(self, form, image_form):
        form.instance.author = self.request.user
        self.object = form.save()
        image_form.instance.book = self.object
        image_form.save()
        return super().form_valid(form)

    def form_invalid(self, form, image_form):
        return self.render_to_response(
            self.get_context_data(form=form, image_form=image_form)
        )

    #def test_func(self):
        #book = self.get_object()
        #if self.request.user == book.author:
            #return True
        #return False

    

reviews/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <title>Book Review</title>
  <style type="text/css">
    .navbar {
      margin: 20px;
      min-height: 70px;
      font-size: 25px;
    }
    .navbar-brand {
      font-size: 30px;
      font-weight: bold;
    }
    .navbar-dark .navbar-toggler-icon {
      background-color: #fff;
    }
    .nav-link {
      font-size: 18px;
    }
    .search-container {
      display: flex;
      align-items: center;
    }
    .search-input {
      width: 250px;
      margin-right: 10px;
    }
    .search-btn {
      background-color: #28a745;
      border-color: #28a745;
      color: #fff;
    }
    .search-btn:hover {
      background-color: #218838;
      border-color: #1e7e34;
    }
    h1 {
      font-size: 40px;
      color: #333;
      font-family: 'Arial', sans-serif;
      font-weight: bold;
    }
    .alert {
      font-size: 16px;
      font-weight: bold;
    }
    .page-footer {
      background-color: #f8f9fa;
      color: #333;
      font-size: 14px;
    }
    .page-footer a {
      color: #007bff;
      text-decoration: none;
    }
    footer {
      position:relative;
      bottom: 0;
      width: 100%;
      background-color: #b7e2a0ca; 
      /* padding: 10px 0; */
      margin-top: 500px;
    }
  </style>
</head>
<body>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top" style="border-radius: 10px;">
    <a class="navbar-brand" href="/" style="font-family: cursive;">Book Review</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto" style="font-size: 15px; font-family: cursive;">
        <li class="nav-item active">
          <a class="nav-link" href="/book_list/">Book List<span class="sr-only">(current)</span></a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'book_search' %}">Search</a>
        </li>
      </ul>
    </div>
  </nav>
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }}">{{ message }}</div>
  {% endfor %}
  {% endif %}
  {% block content %}
  {% if user.is_authenticated %}
  <h1 style="margin: 20px; font-family: cursive;"><b>Welcome {{ user.username }}</b></h1>
  {% else %}
  <h1 style="margin: 20px; font-family: cursive;"><b>Welcome to Bookr</b></h1>
  {% endif %}
  {% endblock %}

  <!-- Copyright -->
  <footer>
    <div class="footer-copyright text-center py-3">&copy; 2023 Copyright:
      <a href="#"> Leinad Publications</a>
      <p>Website by: Tech Villian</p>
      <p>Contact information: <a href="mailto:leinadthegr8@gmail.com">leinadthegr8@gmail.com</a></p>
    </div>
  </footer>
  <!-- Copyright -->
  <script>
    // You can add your JavaScript here
  </script>
</body>
</html>

reviews/templates/book_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ book.title }} - Book Details</title>
    <style>
        /* style.css */
    body {
        font-family: Arial, sans-serif;
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        background-color: #f8f8f8;
    }

    h1, h2 {
        color: #333;
    }

    p {
        margin-bottom: 10px;
    }

    ul {
        list-style-type: none;
        padding: 0;
    }

    ul li {
        margin-bottom: 20px;
        border: 1px solid #ccc;
        padding: 10px;
        background-color: #fff;
    }

    form {
        margin-top: 20px;
    }

    label, input, textarea {
        display: block;
        margin-bottom: 10px;
    }

    input, textarea {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
    }

    input[type="submit"] {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        cursor: pointer;
        font-size: 16px;
    }

    input[type="submit"]:hover {
        background-color: #0056b3;
    }

    a {
        color: #007bff;
        text-decoration: none;
    }

    a:hover {
        text-decoration: underline;
    }

    /* .center-image-container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    }

    .center-image {
        max-width: 100%;
        max-height: 100%;
    } */

    </style>
</head>
<body>
    <div style="background-color: #b7e2a0ca; padding: 30px; border-radius: 20px;">
        <h3><a href="{% url 'book_list' %}">Back</a></h3>
        <div class="center-image-container">
            <img src="{{ book.image.url }}" alt="{{ book.title }} Image" width="500" height="500" class="center-image" style="margin-left: 100px;">
        </div>
        <h1>{{ book.title|capfirst }}</h1>
        <p>Author: {{ book.publisher.name }}</p>
        <p>Genres:
            {% for genre in book.genre_set.all %}
                {{ genre.genre }}
            {% endfor %}
        </p>
        <p>Contributor: {{ book.contributors.get|capfirst }}</p>
        <p>Publication Date: {{ book.publication_date }}</p>
        <p>ISBN: {{ book.isbn }}</p>
        <div>
            <a href="{% url 'book-update' pk=book.pk %}">Update</a>
        </div>
        <h2>Reviews:</h2>
        <ul>
            {% for review in reviews|slice:":3" %}
                <li>
                    Rating: {{ review.rating|capfirst }}<br>
                    Comment: {{ review.content|capfirst }}<br>
                    Posted by: {{ review.creator.username|capfirst }}<br>
                    Date Posted: {{ review.date_created|capfirst }}
                </li>
            {% endfor %}
        </ul>
        {% if user.is_authenticated %}
            <h2>Submit a Review</h2>
            <form method="post" action="{% url 'submit_review' book.id %}">
                {% csrf_token %}
                <label for="rating">Rating:</label>
                <input type="number" name="rating" min="1" max="5" required><br>
                <label for="comment">Comment:</label><br>
                <textarea name="comment" required></textarea><br>
                <input type="submit" value="Submit">
            </form>
        {% else %}
            <p><a href="{% url 'login' %}?next=/book_detail/{{ book.id }} ">Log in</a> to submit a review.</p>
        {% endif %}
    </div>
</body>
</html>

reviews/templates/book_list.html
{% extends 'base.html' %}

{% block content %}
<div class="dropdown" style="margin-left: 20px; margin-bottom: 10px;">
  <button class="btn btn-secondary" id="genreDropdown">Genre</button>
  <div class="dropdown-menu" id="genreMenu">
    {% for genre in genres %}
      <a class="dropdown-item" href="{% url 'books_by_genre' genre.genre %}">{{ genre.genre }}</a>
    {% endfor %}
  </div>
</div>

<script>
  document.getElementById("genreDropdown").addEventListener("click", function() {
    document.getElementById("genreMenu").classList.toggle("show");
  });

  window.onclick = function(event) {
    if (!event.target.matches('.btn')) {
      var dropdowns = document.getElementsByClassName("dropdown-menu");
      var i;
      for (i = 0; i < dropdowns.length; i++) {
        var openDropdown = dropdowns[i];
        if (openDropdown.classList.contains('show')) {
          openDropdown.classList.remove('show');
        }
      }
    }
  }
</script>

<ul class="list-group">
  {% for item in books %}
  <li class="list-group-item">
      <a href="{% url 'book_detail' item.id %}">{{ item.title|capfirst }}</a>
  </li>
  {% endfor %}
</ul>
<div style="padding: 20px;">
  <a href="{% url 'book-create' %}" class="btn btn-primary">Add new book</a>
</div>

{% endblock %}

reviews/templates/genresort.html
{% extends 'base.html' %}

{% block title %}Books by Genre: {{ genre_type }}{% endblock %}

{% block content %}
    <h1>Books by Genre: {{ genre_type }}</h1>
    <ul>
        {% for book in books %}
            <li>
                <a href="{% url 'book_detail' book.id %}">{{ book.title }}</a> - {{ book.author.name }}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

reviews/templates/search.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Search Results: {{ search_text }}</title>
        <style>
            /* style.css */
            body {
                font-family: Arial, sans-serif;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f8f8f8;
            }

            h1 {
                color: #333;
                margin-bottom: 10px;
            }

            a {
                color: #007bff;
                text-decoration: none;
            }

            em {
                font-style: italic;
            }

            form {
                margin-bottom: 20px;
                border: 10px;
                background-color: #343a40;
                color: #fff;
                padding: 30px;
                border-radius: 5px;
            }

            button {
                background-color: #9bc4f2;
                color: #fff;
                border: none;
                padding: 8px 16px;
                cursor: pointer;
            }

            button:hover {
                background-color: #27bc6d;
            }

            ul {
                list-style-type: none;
                padding: 0;
            }

            ul li {
                margin-bottom: 10px;
            }

            p {
                color: #333;
            }

            p.no-results {
                font-style: italic;
            }
        </style>
    </head>
    <body>
        <form method="get">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Search</button>
        </form>
        {% if results %}
            <h2>Search Results</h2>
            <ul>
                {% for book in results %}
                    <li>
                        <a href="{% url 'book_detail' book.id %}">{{ book.title|capfirst }} by {{ book.publisher.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No results found.</p>
        {% endif %}
        <h3><a href="{% url 'book_list' %}">Back</a></h3>
    </body>
</html>